CREATE DATABASE data_analysis_project;
USE data_analysis_project;

SELECT * FROM customer_behaviour_analysis;

---------------- Business Insight Questions
-- 1)Which category generatest highest revenue?
SELECT category, ROUND(SUM(purchase_amount),2) as highest_revenue
FROM customer_behaviour_analysis
GROUP BY category
ORDER BY highest_revenue desc;

-- 2)Are discount acutally increasing purchase value
SELECT discount_applied, ROUND(SUM(purchase_amount),2) AS total_revenue,
                         ROUND(AVG(purchase_amount),2) As avg_revenue
FROM customer_behaviour_analysis
GROUP BY discount_applied;

-- 3)What is the total revenue generated by male and female customer ?
SELECT gender, ROUND(SUM(purchase_amount),2) as highest_revenue
FROM customer_behaviour_analysis
GROUP BY gender
ORDER BY highest_revenue desc; 

-- 4) Which customer used a discount but still spent more then the average purchase amount ?
SELECT 
customer_id,
purchase_amount,
discount_applied
FROM customer_behaviour_analysis
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_behaviour_analysis)
ORDER BY discount_applied desc limit 10;

-- 5) Which are the top/bottom 5 products with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating),2) as avg_ratings
FROM customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY avg_ratings DESC LIMIT 5;

SELECT item_purchased, ROUND(AVG(review_rating),2) as avg_ratings
FROM customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY avg_ratings ASC LIMIT 5;

-- 6) Average purchase: Standard vs Express shipping
SELECT shipping_type, COUNT(distinct customer_id) as order_placed,
ROUND(AVG(purchase_amount),2) as avg_purchase,
ROUND(SUM(purchase_amount),2) as revenue
FROM customer_behaviour_analysis
-- WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY revenue desc;

-- 7) Do subscribed customers spend more ? Compare average speed and total revenue between subscribers and non-subscribers
SELECT subscription_status,
COUNT(customer_id) as users,
ROUND(avg(purchase_amount),2) as avg_revenue,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer_behaviour_analysis
GROUP BY subscription_status
ORDER BY total_revenue desc;

-- 8) Top 5 products with highest discount usage %
SELECT * FROM customer_behaviour_analysis;
SELECT  item_purchased, COUNT(item_purchased) as total_number_of_times_sold,
COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) AS Number_of_times_sold_when_discount_applied,
COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS discount_percent
FROM customer_behaviour_analysis
GROUP BY item_purchased
order by discount_percent desc limit 5;

-- 9) Segment customer into new, returing and loyal based on their total number of previous,
-- purchased and show the count of each segment
SELECT 
CASE 
    WHEN previous_purchases = '0' THEN 'New Customer'
    WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
ELSE 'Loyal Customers'
END AS customer_segment,
COUNT(*) AS customer_count
FROM customer_behaviour_analysis
GROUP BY CASE
    WHEN previous_purchases = '0' THEN 'New Customer'
    WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
ELSE 'Loyal Customers'
END;

-- 10) What are the top 3 most purchased products within each category
WITH CTE AS(SELECT category,item_purchased, COUNT(item_purchased) as most_purchased,
RANK() over(partition by category ORDER BY count(item_purchased)desc) as RNK
FROM customer_behaviour_analysis
GROUP BY category,item_purchased)
SELECT * FROM CTE
WHERE RNK<=3;

-- 11) Are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
SELECT 
CASE 
    WHEN previous_purchases > 5 THEN 'Repeat Buyers'
    ELSE 'Normal Buyers'
END AS customer_type,
subscription_status,
COUNT(*) AS customer_count,
COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(PARTITION BY CASE
                                  WHEN previous_purchases > 5 THEN 'Repeat Buyers'
                                  ELSE 'Normal Buyers'
                                  END) AS percents
FROM customer_behaviour_analysis
GROUP BY CASE 
    WHEN previous_purchaseS > 5 THEN 'Repeat Buyers'
    ELSE 'Normal Buyers'
END,subscription_status;
select * from customer_behaviour_analysis;

-- 12) Wgat us tge revenue contribution of each age group?
SELECT
    CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35' 
        WHEN age BETWEEN 36 AND 50 THEN '36-50' 
        ELSE '51+'
    END AS age_group,
    
    ROUND(SUM(purchase_amount), 2) AS total_revenue

FROM customer_behaviour_analysis

GROUP BY 
    CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35' 
        WHEN age BETWEEN 36 AND 50 THEN '36-50' 
        ELSE '51+'
    END

ORDER BY total_revenue DESC;

SELECT @@hostname;